version: '3.3'
services:
  zappa:
    restart: always
    build: .
    command: ['bash']
    volumes:
      - .:/var/task
      - ~/.aws/:/root/.aws
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal
    volumes:
      - community-map-dynamo-db:/home/dynamodblocal
    ports:
      - "8010:8000"

volumes:
  community-map-dynamo-db:
